const data = [
  {
    owner: "danrfq",
    repo: "jishacum",
    link: "https://github.com/danrfq/jishacum",
    description: "A debugging and testing container for discordrb bots.",
    image: "https://opengraph.githubassets.com/1/danrfq/jishacum",
    language: "Ruby",
    languageColor: "#701516",
    stars: "1",
    forks: 0,
  },
  {
    owner: "danrfq",
    repo: "upcomov",
    link: "https://github.com/danrfq/upcomov",
    description: "Get upcoming movies from Metacritic.",
    image: "https://opengraph.githubassets.com/1/danrfq/upcomov",
    language: "Rust",
    languageColor: "#dea584",
    stars: "1",
    forks: 0,
  },
  {
    owner: "danrfq",
    repo: "danrfq.github.io",
    link: "https://github.com/danrfq/danrfq.github.io",
    description: "My personal website.",
    image: "https://opengraph.githubassets.com/1/danrfq/danrfq.github.io",
    language: "CSS",
    languageColor: "#563d7c",
    stars: "1",
    forks: 0,
  },
  {
    owner: "danrfq",
    repo: "thingsbycm",
    link: "https://github.com/danrfq/thingsbycm",
    description:
      "A program that shows things that are measured around the inputted centimeters.",
    image: "https://opengraph.githubassets.com/1/danrfq/thingsbycm",
    language: "Ruby",
    languageColor: "#701516",
    stars: "1",
    forks: 0,
  },
  {
    owner: "danrfq",
    repo: "trivia-time",
    link: "https://github.com/danrfq/trivia-time",
    description: "A simple Trivia program.",
    image: "https://opengraph.githubassets.com/1/danrfq/trivia-time",
    language: "Rust",
    languageColor: "#dea584",
    stars: "1",
    forks: 0,
  },
  {
    owner: "danrfq",
    repo: "fmylife",
    link: "https://github.com/danrfq/fmylife",
    description: "Generates a random FML story from https://fmylife.com.",
    image: "https://opengraph.githubassets.com/1/danrfq/fmylife",
    website: "https://fmylife.com",
    language: "JavaScript",
    languageColor: "#f1e05a",
    stars: "1",
    forks: 0,
  },
];
